// Auto-generated by Firefoo v1.3.17 on 2022-07-11 17:58:39 UTC
import type { Timestamp } from "firebase/firestore";

export interface Order {
  charges_id: string;
  created_at: Timestamp;
  customers_id: string;
  deliver_to: DeliverTo;
  /**
   * Do not use `distance` to calculate delivery fee. Read from `deliveryFee`
   * instead, because the calculation for `deliveryFee` may change over time.
   */
  distance?: number;
  deliveryFee?: number;
  processingFee?: number;
  serviceFee?: number;
  smallOrderFee?: number;
  order_items: OrderItem[];
  restaurant_id: string;
  subTotal?: number;
  discount?: number;
  tax?: number;
  tip: number;
  total: number;
  waitTime?: number;
}

export interface ApiOrder extends Omit<Order, "created_at"> {
  created_at: string;
}

interface DeliverTo {
  address: string;
  appartmentNo: string;
  customerLocation?: CustomerLocation;
  dropoff: string;
  dropoff_note: string;
  email: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
}

interface CustomerLocation {
  lat: number;
  lng: number;
}

export interface OrderItem {
  choices: Choice[];
  item_description: string;
  item_id: string;
  /**
   * The meal_Price of the item, i.e., the price of it without any options selected
   */
  item_price?: number;
  /**
   * The meal_Price + the price of all options
   */
  item_total: string;
  optionalChoices?: OptionalChoice[];
  optionsTotal: number;
  qty: number;
  tipPlaceHolderText?: string;
}

export interface Choice {
  name: string;
  price: number;
  qty: number;
}

interface OptionalChoice {
  name: string;
  price: number;
  qty: number;
}
