name: Test, lint and check formatting

on:
  pull_request:
    branches: ["main"]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:ci

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check
